[package]
name = "sys-rs"
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["yrakcaz <zackaryayoun@gmail.com>"]
repository = "https://github.com/yrakcaz/sys-rs"

[[bin]]
name = "strace-rs"
path = "src/strace.rs"

[dependencies]
libc = "0.2.153"
nix = { version = "0.28.0", features = ["process", "ptrace"] }
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
