[package]
name = "sys-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["yrakcaz <zackaryayoun@gmail.com>"]
repository = "https://github.com/yrakcaz/sys-rs"

[[bin]]
name = "strace-rs"
path = "src/strace.rs"

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.153"
maplit = "1.0.2"
nix = { version = "0.28.0", features = ["process", "ptrace"] }
